[package]
name = "cryptoxide"
version = "0.6.4"
authors = ["Vincent Hanquez <vincent@coretype.io>", "Nicolas Di Prima <nicolas@prime-type.co.uk>", "The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/typed-io/cryptoxide/"
repository = "https://github.com/typed-io/cryptoxide/"
description = "pure implementation of various common modern cryptographic algorithms, WASM compatible"
keywords = [ "Crypto", "Cryptography", "Modern", "Pure" ]
categories = [ "cryptography" ]
edition = '2021'
rust-version = "1.79.0"

[badges]

[lib]
doctest = false

[build-dependencies]

[dependencies]

[features]
default = [
    "aes",
    "aes-gcm",
    "argon2",
    "blake2",
    "blake3",
    "sha1",
    "sha2",
    "sha3",
    "ripemd160",
    "chacha",
    "salsa",
    "hkdf",
    "hmac",
    "pbkdf2",
    "poly1305",
    "scrypt",
    "curve25519",
    "ed25519",
    "x25519",
    "mlkem",
    "mldsa"
]
aes = []
aes-gcm = ["aes"]
blake2 = []
blake3 = []
sha1 = []
sha2 = []
sha3 = []
ripemd160 = []
digest = []

chacha = []
salsa = []

hkdf = ["hmac"]
hmac = []
pbkdf2 = ["hmac"]
scrypt = ["pbkdf2", "hmac", "sha2"]
argon2 = ["blake2"]
poly1305 = []

curve25519 = []
ed25519 = ["curve25519"]
x25519 = ["curve25519"]

mlkem = ["sha3"]
# the pre hash variant of ML-DSA signs SHA-2 digests as well as SHA-3 ones
mldsa = ["sha3", "sha2"]

with-bench = []
force-32bits = []
